launch-prefix=niri msg action spawn --

prompt="▶  "
lines=10
font=sans-serif
password-character=•

# Catppuccin Mocha with 'flamingo' accent and Adwaita (GTK default) background.
#   https://github.com/catppuccin/fuzzel
#   https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-4-22/gtk/theme/Default/_colors.scss
[colors]
background=353535ee
text=cdd6f4ff
prompt=bac2deff
placeholder=7f849cff
input=cdd6f4ff
match=3584e4ff
selection=585b70ff
selection-text=cdd6f4ff
selection-match=f2cdcdff
counter=7f849cff
border=f2cdcdff
