if [[ ${OSTYPE} == linux* ]] && [[ -e /etc/debian_version ]]; then
  # Disable keyboard changes and compinit in /etc/zsh/zshrc.
  # Zim takes care of this.
  DEBIAN_PREVENT_KEYBOARD_CHANGES=1
  skip_global_compinit=1
fi

# vim: ft=zsh sw=2 ts=2 et
