if [[ ${OSTYPE} == linux* ]]; then
  if [[ -e /etc/debian_version ]]; then
    # Disable keyboard changes and compinit in /etc/zsh/zshrc.
    # Zim takes care of this.
    DEBIAN_PREVENT_KEYBOARD_CHANGES=1
    skip_global_compinit=1
  elif [[ -e /etc/NIXOS ]]; then
    # Disable NixOS' global shell configuration altogether.
    # It interferes with Zim.
    setopt no_global_rcs
  fi
elif [[ ${OSTYPE} == darwin* ]] && [[ -n "$__NIX_DARWIN_SET_ENVIRONMENT_DONE" ]]; then
  setopt no_global_rcs
fi

# Source local environment
if [[ -s ${ZDOTDIR:-${HOME}}/.zshenv.local ]]; then
  . ${ZDOTDIR:-${HOME}}/.zshenv.local
fi

# vim: ft=zsh sw=2 ts=2 et
