

#
# User configuration sourced by interactive shells
#

export EDITOR='vim'
export VISUAL='vim'

bindkey -v # vi key bindings

# BSD ls colors for Solarized color scheme
# see `man 1 ls`
[[ "$(uname)" == 'Darwin' ]] && export LSCOLORS=exfxfeaeBxxehehbadacea

GPG_TTY="$(tty)"
export GPG_TTY

# Source local environment
[[ -s ${ZDOTDIR:-${HOME}}/.zlocal ]] && source ${ZDOTDIR:-${HOME}}/.zlocal

# Change default zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh
